import React, { useState, useMemo } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import {
  Activity,
  Clock,
  ShieldAlert,
  CheckCircle2,
  AlertTriangle,
  Zap,
  Play,
  Pause,
  Layers,
  Route,
  MapPin,
  Package,
  Search,
  ArrowRight,
  Truck,
  Store,
  Compass,
  Navigation,
  Info,
  Sliders,
  Eye
} from 'lucide-react';
import { useMaterialFlow } from '../../../context/MaterialFlowContext';
import { sortPocStations } from '../../../utils/pocSorter';
import { getPocSpaceTrolleysMax, filterInventoryByLine, getPartLineCode } from '../../../utils/calculations';

import { ExcelRequiredPlaceholder } from '../../common/ExcelRequiredPlaceholder';

export const LineFeedingMonitorView: React.FC = () => {
  const {
    inventoryStates,
    parts,
    stations,
    selectedAssemblyLine,
    setSelectedAssemblyLine,
    triggerManualReplenishment,
    dispatchEmergencyTrip,
  } = useMaterialFlow();

  const [selectedTrack, setSelectedTrack] = useState<'ALL' | 'PL' | 'ML'>('ALL');
  const [selectedPartNo, setSelectedPartNo] = useState<string | null>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [isAnimating, setIsAnimating] = useState(true);

  // Filter inventory states based on Assembly Line, Track (PL vs ML) & Search Query
  const filteredInventoryStates = useMemo(() => {
    const lineFiltered = filterInventoryByLine(inventoryStates, parts, selectedAssemblyLine);
    return lineFiltered.filter((state) => {
      const part = parts.find((p) => p.partNo === state.partNo);
      const pocUpper = state.pocPoint.toUpperCase();

      // Search matching
      const matchesSearch =
        state.pocPoint.toLowerCase().includes(searchQuery.toLowerCase()) ||
        state.partNo.toLowerCase().includes(searchQuery.toLowerCase()) ||
        (part?.description || '').toLowerCase().includes(searchQuery.toLowerCase());

      if (!matchesSearch) return false;

      // Track Filter: PL (PL-29 to PL-01) vs ML (ML-01 to ML-48)
      const isPL = pocUpper.startsWith('PL') || pocUpper.includes('PRE');
      const isML = pocUpper.startsWith('ML') || pocUpper.includes('MAIN');

      if (selectedTrack === 'PL' && !isPL) return false;
      if (selectedTrack === 'ML' && !isML) return false;

      return true;
    });
  }, [inventoryStates, parts, searchQuery, selectedTrack, selectedAssemblyLine]);

  const sortedInventoryStates = useMemo(() => sortPocStations(filteredInventoryStates), [filteredInventoryStates]);

  // Active highlighted part
  const activePartState = useMemo(() => {
    if (!selectedPartNo) return sortedInventoryStates[0] || inventoryStates[0] || null;
    return sortedInventoryStates.find((s) => s.partNo === selectedPartNo) || sortedInventoryStates[0] || null;
  }, [selectedPartNo, sortedInventoryStates, inventoryStates]);

  const [selectedCustomStation, setSelectedCustomStation] = useState<string | null>(null);
  const [showAutoStations, setShowAutoStations] = useState(true);

  // Helper for line station limits
  const getLineMaxStations = (lineCode: string) => {
    if (lineCode === '1VCON300') return { plMax: 31, mlMax: 37 };
    if (lineCode === '1VCON200') return { plMax: 31, mlMax: 37 };
    return { plMax: 29, mlMax: 48 }; // 1VCON100
  };

  // Helper for track bar Y position
  const getTrackY = (lineCode: string, track: 'PL' | 'ML', currentSelectedLine: string) => {
    if (currentSelectedLine !== 'ALL') {
      return track === 'ML' ? 260 : 315;
    }
    if (lineCode === '1VCON300') {
      return track === 'ML' ? 100 : 145;
    } else if (lineCode === '1VCON200') {
      return track === 'ML' ? 250 : 295;
    } else {
      return track === 'ML' ? 400 : 445;
    }
  };

  const getTrackYCenter = (lineCode: string, track: 'PL' | 'ML', currentSelectedLine: string) => {
    return getTrackY(lineCode, track, currentSelectedLine) + 12.5;
  };

  // Auto generate all PL & ML station numbers per line matching the diagram
  const autoGeneratedStations = useMemo(() => {
    const list: { id: string; name: string; line: string; track: 'PL' | 'ML'; x: number; y: number }[] = [];
    const linesToProcess = selectedAssemblyLine === 'ALL' ? ['1VCON300', '1VCON200', '1VCON100'] : [selectedAssemblyLine];

    linesToProcess.forEach((lineCode) => {
      const { plMax, mlMax } = getLineMaxStations(lineCode);
      const plYCenter = getTrackYCenter(lineCode, 'PL', selectedAssemblyLine);
      const mlYCenter = getTrackYCenter(lineCode, 'ML', selectedAssemblyLine);

      // Generate PL Stations (PL-Max down to PL-01)
      for (let i = plMax; i >= 1; i--) {
        const numStr = i < 10 ? `0${i}` : `${i}`;
        const name = `PL-${numStr}`;
        const progress = (plMax - i) / (plMax - 1 || 1);
        const x = 415 + Math.round(progress * 510);
        list.push({ id: `${lineCode}-${name}`, name, line: lineCode, track: 'PL', x, y: plYCenter });
      }

      // Generate ML Stations (ML-01 up to ML-Max)
      for (let i = 1; i <= mlMax; i++) {
        const numStr = i < 10 ? `0${i}` : `${i}`;
        const name = `ML-${numStr}`;
        const progress = (i - 1) / (mlMax - 1 || 1);
        const x = 415 + Math.round(progress * 510);
        list.push({ id: `${lineCode}-${name}`, name, line: lineCode, track: 'ML', x, y: mlYCenter });
      }
    });

    return list;
  }, [selectedAssemblyLine]);

  // Active target station coordinate calculation
  const activeTargetPoint = useMemo(() => {
    // 1. If custom station is selected, match from auto generated stations
    if (selectedCustomStation) {
      const match = autoGeneratedStations.find((s) => s.id === selectedCustomStation || `${s.line}-${s.name}` === selectedCustomStation || s.name === selectedCustomStation);
      if (match) {
        return { ...match, isInventoryPart: false };
      }
    }

    // 2. Fall back to active part state from inventory
    if (activePartState) {
      const poc = activePartState.pocPoint.toUpperCase();
      const isML = poc.startsWith('ML') || poc.includes('MAIN');
      const track: 'PL' | 'ML' = isML ? 'ML' : 'PL';
      const numMatch = poc.match(/\d+/);
      const stationNum = numMatch ? parseInt(numMatch[0], 10) : 1;

      let lineCode = selectedAssemblyLine !== 'ALL' ? selectedAssemblyLine : '1VCON100';
      if (selectedAssemblyLine === 'ALL') {
        const part = parts.find((p) => p.partNo === activePartState.partNo);
        if (part?.assemblyLine) {
          lineCode = part.assemblyLine;
        } else if (poc.includes('300') || poc.includes('CON300')) {
          lineCode = '1VCON300';
        } else if (poc.includes('200') || poc.includes('CON200')) {
          lineCode = '1VCON200';
        } else {
          lineCode = '1VCON100';
        }
      }

      const { plMax, mlMax } = getLineMaxStations(lineCode);
      let progress = 0;
      if (isML) {
        progress = Math.min(1, Math.max(0, (stationNum - 1) / (mlMax - 1 || 1)));
      } else {
        progress = Math.min(1, Math.max(0, (plMax - stationNum) / (plMax - 1 || 1)));
      }

      const x = 415 + Math.round(progress * 510);
      const y = getTrackYCenter(lineCode, track, selectedAssemblyLine);

      return {
        id: `active-${activePartState.partNo}-${activePartState.pocPoint}`,
        name: activePartState.pocPoint,
        line: lineCode,
        track,
        x,
        y,
        isInventoryPart: true,
      };
    }

    return { id: 'default', name: 'PL-01', line: '1VCON100', track: 'PL', x: 925, y: 327.5, isInventoryPart: false };
  }, [selectedCustomStation, activePartState, autoGeneratedStations, selectedAssemblyLine, parts]);

  // Compute travel path string for the target point
  const targetPathD = useMemo(() => {
    const startX = 85;
    const startY = 57.5;
    const gangwayX = 309;
    const targetY = activeTargetPoint.y;
    // If it is an inventory part station (60px rectangular badge), stop 35px to the left (at the edge of the badge) to keep text fully visible.
    const targetX = activeTargetPoint.isInventoryPart ? activeTargetPoint.x - 35 : activeTargetPoint.x;

    return `M ${startX} ${startY} L ${gangwayX} ${startY} L ${gangwayX} ${targetY} L ${targetX} ${targetY}`;
  }, [activeTargetPoint]);

  // Assembly Lines structure with PL and ML tracks
  const allLineConfigs = [
    { code: '1VCON300', label: '1VCON300 ASSEMBLY LINE', mlRange: 'ML-01 → ML-37', plRange: 'PL-31 → PL-01', y: 120, color: '#10b981' },
    { code: '1VCON200', label: '1VCON200 ASSEMBLY LINE', plRange: 'PL-31 → PL-01', mlRange: 'ML-01 → ML-37', y: 270, color: '#10b981' },
    { code: '1VCON100', label: '1VCON100 ASSEMBLY LINE', plRange: 'PL-29 → PL-01', mlRange: 'ML-01 → ML-48', y: 420, color: '#10b981' },
  ];

  // Render only selected line when specific line chosen
  const lineConfigsToRender = useMemo(() => {
    if (selectedAssemblyLine === 'ALL') {
      return allLineConfigs;
    }
    const matched = allLineConfigs.find((l) => l.code === selectedAssemblyLine);
    if (!matched) return allLineConfigs;
    return [{ ...matched, y: 280 }];
  }, [selectedAssemblyLine]);

  // Map POC points to Y & X coordinates on the SVG map (Store in TOP-LEFT)
  const pocCoordinates = useMemo(() => {
    const coords: Record<string, { x: number; y: number; line: string; track: 'PL' | 'ML'; pocPoint: string; parts: string[] }> = {};

    sortedInventoryStates.forEach((state) => {
      const poc = state.pocPoint.toUpperCase();
      const isML = poc.startsWith('ML') || poc.includes('MAIN');
      const track: 'PL' | 'ML' = isML ? 'ML' : 'PL';
      const numMatch = poc.match(/\d+/);
      const stationNum = numMatch ? parseInt(numMatch[0], 10) : 1;

      let lineCode = selectedAssemblyLine !== 'ALL' ? selectedAssemblyLine : '1VCON100';
      if (selectedAssemblyLine === 'ALL') {
        const part = parts.find((p) => p.partNo === state.partNo);
        if (part?.assemblyLine) {
          lineCode = part.assemblyLine;
        } else if (poc.includes('300') || poc.includes('CON300')) {
          lineCode = '1VCON300';
        } else if (poc.includes('200') || poc.includes('CON200')) {
          lineCode = '1VCON200';
        } else {
          lineCode = '1VCON100';
        }
      }

      const key = `${lineCode}-${state.pocPoint}`;

      if (!coords[key]) {
        const { plMax, mlMax } = getLineMaxStations(lineCode);
        let progress = 0;
        if (isML) {
          progress = Math.min(1, Math.max(0, (stationNum - 1) / (mlMax - 1 || 1)));
        } else {
          progress = Math.min(1, Math.max(0, (plMax - stationNum) / (plMax - 1 || 1)));
        }

        const x = 415 + Math.round(progress * 510);
        const y = getTrackYCenter(lineCode, track, selectedAssemblyLine);

        coords[key] = {
          x,
          y,
          line: lineCode,
          track,
          pocPoint: state.pocPoint,
          parts: [state.partNo]
        };
      } else {
        if (!coords[key].parts.includes(state.partNo)) {
          coords[key].parts.push(state.partNo);
        }
      }
    });

    return coords;
  }, [sortedInventoryStates, selectedAssemblyLine, parts]);

  // Compute calculated travel paths from Store (TOP-LEFT) to specific stations
  const travelPaths = useMemo(() => {
    return sortedInventoryStates.map((state, idx) => {
      const part = parts.find((p) => p.partNo === state.partNo);
      return {
        id: `feeding-path-${state.partNo}-${idx}`,
        partNo: state.partNo,
        pocPoint: state.pocPoint,
        description: part?.description || state.pocPoint,
        distanceMeters: part?.loadedDistanceMeters || 194,
        transportMode: part?.transportMode || 'Jumbo Trolley',
        isSelected: activePartState?.partNo === state.partNo,
      };
    });
  }, [sortedInventoryStates, parts, activePartState]);

  // Count stats
  const plCount = sortedInventoryStates.filter((s) => s.pocPoint.toUpperCase().startsWith('PL')).length;
  const mlCount = sortedInventoryStates.filter((s) => s.pocPoint.toUpperCase().startsWith('ML')).length;
  const criticalRiskCount = sortedInventoryStates.filter((s) => s.riskLevel === 'Red').length;
  const warningRiskCount = sortedInventoryStates.filter((s) => s.riskLevel === 'Yellow').length;

  if (parts.length === 0) {
    return <ExcelRequiredPlaceholder />;
  }

  return (
    <div id="line-feeding-monitor-view" className="space-y-6 font-sans">
      
      {/* 1. HEADER CONTROL TOWER */}
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-4 shadow-xl flex flex-col lg:flex-row lg:items-center justify-between gap-4">
        <div>
          <h2 className="text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2 font-mono uppercase tracking-wider">
            <Activity className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />
            Line Feeding Monitor & Calculated Travel Paths
          </h2>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
            Top-Left Store dispatching directly to PL Track (PL-01 to PL-29) and ML Track (ML-01 to ML-48) for {selectedAssemblyLine}
          </p>
        </div>

        {/* Color Rules Legend */}
        <div className="flex flex-wrap items-center gap-3 text-xs bg-slate-50 dark:bg-slate-950 px-3.5 py-2 rounded-xl border border-slate-200 dark:border-slate-800 font-mono">
          <div className="flex items-center space-x-1.5">
            <span className="w-2.5 h-2.5 rounded-full bg-emerald-500 inline-block"></span>
            <span className="text-emerald-700 dark:text-emerald-300 font-semibold">Green &gt;2h</span>
          </div>
          <div className="flex items-center space-x-1.5">
            <span className="w-2.5 h-2.5 rounded-full bg-amber-500 inline-block"></span>
            <span className="text-amber-700 dark:text-amber-300 font-semibold">Yellow 1-2h</span>
          </div>
          <div className="flex items-center space-x-1.5">
            <span className="w-2.5 h-2.5 rounded-full bg-rose-500 inline-block animate-ping"></span>
            <span className="text-rose-700 dark:text-rose-300 font-semibold">Red &lt;1h</span>
          </div>
        </div>
      </div>

      {/* 2. DYNAMIC FILTERS: ASSEMBLY LINE & TRACK (PL / ML) */}
      <div className="bg-white dark:bg-slate-950 p-4 rounded-2xl border border-slate-200 dark:border-slate-800 space-y-3 font-mono shadow-sm">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-3">
          
          {/* Assembly Line Selector */}
          <div className="flex items-center gap-2">
            <span className="text-xs text-slate-500 dark:text-slate-400 font-bold uppercase flex items-center gap-1.5">
              <Layers className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
              SELECT ASSEMBLY LINE:
            </span>
            <div className="flex items-center bg-slate-100 dark:bg-slate-900 p-1 rounded-xl border border-slate-200 dark:border-slate-800 gap-1">
              {(['ALL', '1VCON300', '1VCON200', '1VCON100'] as const).map((lineCode) => (
                <button
                  key={lineCode}
                  onClick={() => setSelectedAssemblyLine(lineCode as any)}
                  className={`px-3 py-1.5 rounded-lg transition-all cursor-pointer font-extrabold text-xs ${
                    selectedAssemblyLine === lineCode
                      ? 'bg-emerald-600 text-white shadow-lg'
                      : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
                  }`}
                >
                  {lineCode}
                </button>
              ))}
            </div>
          </div>

          {/* PL Track vs ML Track Selector */}
          <div className="flex items-center gap-2">
            <span className="text-xs text-slate-500 dark:text-slate-400 font-bold uppercase flex items-center gap-1.5">
              <Route className="w-4 h-4 text-cyan-600 dark:text-cyan-400" />
              FEEDING TRACK:
            </span>
            <div className="flex items-center bg-slate-100 dark:bg-slate-900 p-1 rounded-xl border border-slate-200 dark:border-slate-800 gap-1">
              <button
                onClick={() => setSelectedTrack('ALL')}
                className={`px-3 py-1.5 rounded-lg transition-all cursor-pointer font-extrabold text-xs ${
                  selectedTrack === 'ALL' ? 'bg-blue-600 text-white shadow-lg' : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
                }`}
              >
                ALL TRACKS
              </button>
              <button
                onClick={() => setSelectedTrack('PL')}
                className={`px-3 py-1.5 rounded-lg transition-all cursor-pointer font-extrabold text-xs ${
                  selectedTrack === 'PL' ? 'bg-cyan-600 text-white shadow-lg' : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
                }`}
              >
                PL TRACK (PL-01 to PL-29) [{plCount}]
              </button>
              <button
                onClick={() => setSelectedTrack('ML')}
                className={`px-3 py-1.5 rounded-lg transition-all cursor-pointer font-extrabold text-xs ${
                  selectedTrack === 'ML' ? 'bg-purple-600 text-white shadow-lg' : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
                }`}
              >
                ML TRACK (ML-01 to ML-48) [{mlCount}]
              </button>
            </div>
          </div>

        </div>

        {/* Search & Active Part Picker */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-3 pt-2 border-t border-slate-200 dark:border-slate-800/80">
          <div className="flex items-center gap-2 flex-1">
            <span className="text-xs text-slate-500 dark:text-slate-400 font-bold shrink-0">VISUALIZE PATH FOR:</span>
            <select
              value={activePartState?.partNo || ''}
              onChange={(e) => setSelectedPartNo(e.target.value)}
              className="bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 text-emerald-700 dark:text-emerald-400 font-extrabold rounded-xl px-3 py-1.5 focus:outline-none focus:border-emerald-500 w-full max-w-md text-xs cursor-pointer"
            >
              {sortedInventoryStates.map((s, idx) => {
                const p = parts.find((pt) => pt.partNo === s.partNo);
                return (
                  <option key={`${s.partNo}-${s.pocPoint}-${idx}`} value={s.partNo}>
                    {s.pocPoint} ({s.partNo}) - {p?.description} [Stock: {s.coverageHours}h]
                  </option>
                );
              })}
            </select>
          </div>

          <div className="relative w-full md:w-64">
            <input
              type="text"
              placeholder="Filter Station / Part..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-slate-900 dark:text-white px-3 py-1.5 pl-8 rounded-xl focus:outline-none focus:border-emerald-500 text-xs placeholder:text-slate-400"
            />
            <Search className="w-3.5 h-3.5 text-slate-400 absolute left-2.5 top-2.5" />
          </div>
        </div>
      </div>

      {/* 3. CALCULATED TRAVEL PATH DYNAMIC VISUAL MAP (STORE AT TOP-LEFT) */}
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-4 shadow-xl space-y-3 font-sans">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 pb-2 border-b border-slate-200 dark:border-slate-800">
          <div className="flex items-center gap-2">
            <Route className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />
            <h3 className="text-sm font-bold text-slate-900 dark:text-white font-mono uppercase">
              STORE (TOP-LEFT) TO {selectedAssemblyLine} ASSEMBLY LINE STATIONS MAP
            </h3>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => setShowAutoStations(!showAutoStations)}
              className={`px-2.5 py-1 rounded-xl border text-xs font-mono font-bold flex items-center gap-1.5 cursor-pointer transition-all ${
                showAutoStations ? 'bg-cyan-50 dark:bg-cyan-950/80 border-cyan-300 dark:border-cyan-700 text-cyan-800 dark:text-cyan-300' : 'bg-slate-100 dark:bg-slate-950 border-slate-200 dark:border-slate-800 text-slate-700 dark:text-slate-400'
              }`}
            >
              <Eye className="w-3.5 h-3.5" />
              <span>{showAutoStations ? 'Auto-Stations Visible' : 'Show Auto-Stations'}</span>
            </button>

            <button
              onClick={() => setIsAnimating(!isAnimating)}
              className="px-2.5 py-1 rounded-xl bg-slate-100 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 text-xs text-emerald-700 dark:text-emerald-400 font-mono font-bold flex items-center gap-1.5 cursor-pointer"
            >
              {isAnimating ? <Play className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400" /> : <Pause className="w-3.5 h-3.5 text-slate-400" />}
              <span>{isAnimating ? 'Paths Animating' : 'Static View'}</span>
            </button>
          </div>
        </div>

        {/* Auto Generated Station Quick Picker */}
        {showAutoStations && (
          <div className="bg-slate-50 dark:bg-slate-950/90 p-2.5 rounded-xl border border-slate-200 dark:border-slate-800 space-y-1.5 font-mono text-xs">
            <div className="flex items-center justify-between text-[11px]">
              <span className="text-slate-600 dark:text-slate-400 font-bold uppercase flex items-center gap-1">
                <Sliders className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400" />
                AUTO-GENERATED STATIONS ({autoGeneratedStations.length} Total):
              </span>
              <span className="text-amber-700 dark:text-amber-400 font-bold">
                Target: {activeTargetPoint.name} ({activeTargetPoint.line} {activeTargetPoint.track})
              </span>
            </div>
            <div className="flex flex-wrap gap-1 max-h-20 overflow-y-auto pr-1 custom-scrollbar">
              {autoGeneratedStations.map((st) => {
                const isSelected = activeTargetPoint.line === st.line && activeTargetPoint.name === st.name;
                return (
                  <button
                    key={st.id}
                    onClick={() => {
                      setSelectedCustomStation(st.id);
                      setSelectedPartNo(null);
                    }}
                    className={`px-2 py-0.5 rounded text-[10px] font-bold border transition-all cursor-pointer ${
                      isSelected
                        ? st.track === 'PL'
                          ? 'bg-cyan-600 border-cyan-400 text-white shadow'
                          : 'bg-purple-600 border-purple-400 text-white shadow'
                        : st.track === 'PL'
                        ? 'bg-white dark:bg-slate-900 border-slate-200 dark:border-slate-800 text-cyan-700 dark:text-cyan-400 hover:border-cyan-500'
                        : 'bg-white dark:bg-slate-900 border-slate-200 dark:border-slate-800 text-purple-700 dark:text-purple-400 hover:border-purple-500'
                    }`}
                  >
                    {st.name}
                  </button>
                );
              })}
            </div>
          </div>
        )}

        {/* Active Route Header Bar (Clean non-blocking layout) */}
        {activePartState && (
          <div className="bg-slate-50 dark:bg-slate-900/90 border border-slate-200 dark:border-slate-700/80 rounded-xl p-3 flex flex-wrap items-center justify-between gap-3 text-xs font-mono shadow-md">
            <div className="flex items-center gap-2">
              <span className="px-2.5 py-1 rounded bg-emerald-100 dark:bg-emerald-950 text-emerald-800 dark:text-emerald-400 font-extrabold border border-emerald-300 dark:border-emerald-500/30 text-[10px] uppercase">
                Active Route
              </span>
              <span className="text-slate-900 dark:text-white font-extrabold text-sm">{activePartState.pocPoint}</span>
              <span className="text-cyan-700 dark:text-cyan-400 text-xs font-bold">({activePartState.partNo})</span>
            </div>

            <div className="flex items-center gap-4 text-[11px]">
              <div>
                <span className="text-slate-500 dark:text-slate-400">Line: </span>
                <strong className="text-emerald-700 dark:text-emerald-400 font-bold">{selectedAssemblyLine}</strong>
              </div>
              <div>
                <span className="text-slate-500 dark:text-slate-400">Coverage: </span>
                <strong className="text-amber-700 dark:text-amber-300 font-bold">{activePartState.coverageHours} Hours</strong>
              </div>
              <div>
                <span className="text-slate-500 dark:text-slate-400">Risk: </span>
                <strong className={activePartState.riskLevel === 'Green' ? 'text-emerald-700 dark:text-emerald-400 font-bold' : activePartState.riskLevel === 'Yellow' ? 'text-amber-700 dark:text-amber-400 font-bold' : 'text-rose-700 dark:text-rose-400 font-bold'}>
                  {activePartState.riskLevel} Risk
                </strong>
              </div>
              <div>
                <span className="text-slate-500 dark:text-slate-400">Trip Distance: </span>
                <strong className="text-cyan-700 dark:text-cyan-400 font-bold">194M</strong>
              </div>
            </div>
          </div>
        )}

        <div className="relative bg-slate-950 rounded-xl overflow-hidden border border-slate-800 p-2 min-h-[520px]">
          <svg viewBox="0 0 1000 620" className="w-full h-auto select-none">
            <defs>
              <filter id="glowCyanTL" x="-20%" y="-20%" width="140%" height="140%">
                <feGaussianBlur stdDeviation="4" result="blur" />
                <feComposite in="SourceGraphic" in2="blur" operator="over" />
              </filter>
              <filter id="glowGreenTL" x="-20%" y="-20%" width="140%" height="140%">
                <feGaussianBlur stdDeviation="3" result="blur" />
                <feComposite in="SourceGraphic" in2="blur" operator="over" />
              </filter>
              <filter id="glowRedTL" x="-20%" y="-20%" width="140%" height="140%">
                <feGaussianBlur stdDeviation="4" result="blur" />
                <feComposite in="SourceGraphic" in2="blur" operator="over" />
              </filter>
              <linearGradient id="feedingGradTL" x1="0%" y1="0%" x2="100%" y2="100%">
                <stop offset="0%" stopColor="#34d399" />
                <stop offset="50%" stopColor="#38bdf8" />
                <stop offset="100%" stopColor="#f43f5e" />
              </linearGradient>
              <pattern id="feedGrid" width="40" height="40" patternUnits="userSpaceOnUse">
                <path d="M 40 0 L 0 0 0 40" fill="none" stroke="#1e293b" strokeWidth="0.5" strokeDasharray="2,2" />
              </pattern>
            </defs>

            <rect width="1000" height="620" fill="url(#feedGrid)" />

            {/* ------------------------------------------------------------------ */}
            {/* 1. STORES BOX (TOP-LEFT) MATCHING USER DIAGRAM                     */}
            {/* ------------------------------------------------------------------ */}
            <g transform="translate(15, 15)">
              <rect x="0" y="0" width="135" height="85" fill="#030806" stroke="#10b981" strokeWidth="2.5" rx="2" />
              <text x="67" y="32" fill="#ffffff" fontSize="15" fontWeight="bold" textAnchor="middle" fontFamily="sans-serif">
                Stores
              </text>
              <text x="67" y="70" fill="#64748b" fontSize="10" fontWeight="bold" textAnchor="middle" fontFamily="sans-serif" letterSpacing="1">
                CENTRAL HUB
              </text>
            </g>

            {/* 2. HORIZONTAL "MATERIAL MOVEMENT" CORRIDOR */}
            <g transform="translate(150, 32)">
              <rect x="0" y="0" width="140" height="40" fill="#030806" stroke="#10b981" strokeWidth="2" rx="2" />
              <text
                x="70"
                y="13"
                fill="#ffffff"
                fontSize="10"
                fontWeight="bold"
                textAnchor="middle"
                fontFamily="sans-serif"
                letterSpacing="1"
                stroke="#030806"
                strokeWidth="3"
                paintOrder="stroke"
                strokeLinejoin="round"
              >
                MATERIAL TRANSIT
              </text>
            </g>

            {/* 3. VERTICAL "MATERIAL MOVEMENT" GANGWAY */}
            <g transform="translate(290, 72)">
              <rect x="0" y="0" width="38" height="515" fill="#030806" stroke="#10b981" strokeWidth="2.5" rx="2" />
              <text
                x="19"
                y="255"
                fill="#ffffff"
                fontSize="11"
                fontWeight="bold"
                textAnchor="middle"
                fontFamily="sans-serif"
                transform="rotate(-90 19 255)"
                letterSpacing="2"
                stroke="#030806"
                strokeWidth="4"
                paintOrder="stroke"
                strokeLinejoin="round"
              >
                Material movement
              </text>
            </g>

            {/* ------------------------------------------------------------------ */}
            {/* 4. ASSEMBLY LINES WITH VERTICAL LABEL & PL/ML TRACK BARS           */}
            {/* ------------------------------------------------------------------ */}
            {lineConfigsToRender.map((lineItem) => {
              const isSelectedLine = selectedAssemblyLine === 'ALL' || selectedAssemblyLine === lineItem.code;

              const lineBoxY = selectedAssemblyLine !== 'ALL' ? 260 : lineItem.y - 10;
              const mlY = getTrackY(lineItem.code, 'ML', selectedAssemblyLine);
              const plY = getTrackY(lineItem.code, 'PL', selectedAssemblyLine);

              return (
                <g key={`lf-line-${lineItem.code}`} opacity={isSelectedLine ? 1 : 0.25}>
                  {/* Vertical Assembly Line Code Box */}
                  <g transform={`translate(338, ${lineBoxY})`}>
                    <rect x="0" y="0" width="32" height="80" fill="#030806" stroke="#10b981" strokeWidth="2" rx="2" />
                    <text
                      x="16"
                      y="40"
                      fill="#ffffff"
                      fontSize="12"
                      fontWeight="black"
                      textAnchor="middle"
                      fontFamily="monospace"
                      transform="rotate(-90 16 40)"
                    >
                      {lineItem.code}
                    </text>
                  </g>

                  {/* ML TRACK BAR (Top Bar - Red stroke) */}
                  <g transform={`translate(375, ${mlY})`}>
                    <rect x="0" y="0" width="590" height="25" fill="#180505" stroke="#ef4444" strokeWidth="2" rx="2" />
                    {/* Left station box */}
                    <rect x="0" y="0" width="22" height="25" fill="#1c0a00" stroke="#f97316" strokeWidth="1.5" />
                    <text x="11" y="13" fill="#ffffff" fontSize="7" fontWeight="bold" textAnchor="middle" fontFamily="monospace" transform="rotate(-90 11 13)">
                      ML-01
                    </text>
                    {/* Right station box */}
                    <rect x="568" y="0" width="22" height="25" fill="#1c0a00" stroke="#f97316" strokeWidth="1.5" />
                    <text x="579" y="13" fill="#ffffff" fontSize="7" fontWeight="bold" textAnchor="middle" fontFamily="monospace" transform="rotate(-90 579 13)">
                      {lineItem.code === '1VCON100' ? 'ML-48' : 'ML-37'}
                    </text>
                  </g>

                  {/* PL TRACK BAR (Bottom Bar - Green stroke) */}
                  <g transform={`translate(375, ${plY})`}>
                    <rect x="0" y="0" width="590" height="25" fill="#030806" stroke="#10b981" strokeWidth="2" rx="2" />
                    {/* Left station box */}
                    <rect x="0" y="0" width="22" height="25" fill="#09140e" stroke="#10b981" strokeWidth="1.5" />
                    <text x="11" y="13" fill="#ffffff" fontSize="7" fontWeight="bold" textAnchor="middle" fontFamily="monospace" transform="rotate(-90 11 13)">
                      {lineItem.code === '1VCON100' ? 'PL-29' : 'PL-31'}
                    </text>
                    {/* Right station box */}
                    <rect x="568" y="0" width="22" height="25" fill="#09140e" stroke="#10b981" strokeWidth="1.5" />
                    <text x="579" y="13" fill="#ffffff" fontSize="7" fontWeight="bold" textAnchor="middle" fontFamily="monospace" transform="rotate(-90 579 13)">
                      PL-01
                    </text>
                  </g>
                </g>
              );
            })}

            {/* SMOOTH ANIMATED PATH FROM STORES THROUGH MATERIAL MOVEMENT TO STATIONS */}
            {(() => {
              const isCriticalShortage = activePartState?.riskLevel === 'Red' || (activePartState?.coverageHours ?? 2) < 1.0;
              return (
                <g>
                  {/* Outer Pulsing Glow Path (using a parent motion.g to prevent path coordinate 'd' from getting stuck during repeat: Infinity) */}
                  <motion.g
                    initial={{ opacity: 0.6 }}
                    animate={isCriticalShortage ? { opacity: [0.35, 0.95, 0.35] } : { opacity: 0.6 }}
                    transition={isCriticalShortage ? { duration: 1.2, repeat: Infinity, ease: 'easeInOut' } : { duration: 0.4 }}
                  >
                    <motion.path
                      d={targetPathD}
                      animate={{ d: targetPathD }}
                      transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
                      fill="none"
                      stroke={isCriticalShortage ? '#f43f5e' : '#34d399'}
                      strokeWidth={isCriticalShortage ? 8 : 6}
                      filter={isCriticalShortage ? 'url(#glowRedTL)' : 'url(#glowGreenTL)'}
                    />
                  </motion.g>

                  {/* Solid Active Dotted Path */}
                  <motion.path
                    d={targetPathD}
                    animate={{ d: targetPathD }}
                    transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
                    fill="none"
                    stroke={isCriticalShortage ? '#f43f5e' : 'url(#feedingGradTL)'}
                    strokeWidth="3.5"
                    strokeDasharray="6 3"
                  />

                  {/* PULSING DELIVERY TROLLEY ALONG PATH */}
                  {isAnimating && (
                    <circle
                      r="7"
                      fill={isCriticalShortage ? '#f43f5e' : '#34d399'}
                      stroke="#ffffff"
                      strokeWidth="2"
                      filter={isCriticalShortage ? 'url(#glowRedTL)' : 'url(#glowGreenTL)'}
                    >
                      <animateMotion dur={isCriticalShortage ? '1.8s' : '2.8s'} repeatCount="indefinite" path={targetPathD} />
                    </circle>
                  )}

                  {/* DISTANCE BADGE ALONG TOP CORRIDOR */}
                  <g transform="translate(180, 40)">
                    <rect
                      x="0"
                      y="-10"
                      width={isCriticalShortage ? 160 : 105}
                      height="20"
                      rx="5"
                      fill="#0f172a"
                      stroke={isCriticalShortage ? '#f43f5e' : '#10b981'}
                      strokeWidth="1.5"
                    />
                    <text
                      x={isCriticalShortage ? 80 : 52}
                      y="3"
                      fill={isCriticalShortage ? '#fb7185' : '#34d399'}
                      fontSize="9"
                      fontWeight="extrabold"
                      textAnchor="middle"
                      fontFamily="monospace"
                    >
                      {isCriticalShortage
                        ? `CRITICAL ⚡ ${activePartState?.partNo ? parts.find((p) => p.partNo === activePartState.partNo)?.loadedDistanceMeters || 194 : 194}M TRIP`
                        : `${activePartState?.partNo ? parts.find((p) => p.partNo === activePartState.partNo)?.loadedDistanceMeters || 194 : 194}M TRIP`}
                    </text>
                  </g>
                </g>
              );
            })()}

            {/* AUTO GENERATED STATIONS ALONG TRACKS WITH CLEAN UNCLUTTERED BADGES */}
            {showAutoStations &&
              autoGeneratedStations.map((st) => {
                const isSelected = activeTargetPoint.line === st.line && activeTargetPoint.name === st.name;
                const numVal = parseInt(st.name.split('-')[1] || '1', 10);
                const isKeyStation = numVal === 1 || numVal % 5 === 0;

                return (
                  <g
                    key={`st-node-${st.id}`}
                    transform={`translate(${st.x}, ${st.y})`}
                    className="cursor-pointer"
                    onClick={() => {
                      setSelectedCustomStation(st.id);
                      setSelectedPartNo(null);
                    }}
                  >
                    <circle
                      cx="0"
                      cy="0"
                      r={isSelected ? 6 : isKeyStation ? 3.5 : 2}
                      fill={isSelected ? (st.track === 'PL' ? '#10b981' : '#f97316') : isKeyStation ? '#38bdf8' : '#334155'}
                      stroke={st.track === 'PL' ? '#34d399' : '#fb923c'}
                      strokeWidth={isSelected ? 2 : 0.8}
                    />
                    {(isSelected || isKeyStation) && (
                      <text
                        x="0"
                        y="15"
                        fill={isSelected ? '#ffffff' : '#94a3b8'}
                        fontSize={isSelected ? '9' : '7'}
                        fontWeight={isSelected ? 'bold' : 'normal'}
                        textAnchor="middle"
                        fontFamily="monospace"
                      >
                        {st.name}
                      </text>
                    )}
                  </g>
                );
              })}

            {/* INVENTORY PART STATIONS */}
            {(Object.values(pocCoordinates) as { x: number; y: number; line: string; track: 'PL' | 'ML'; pocPoint: string; parts: string[] }[]).map((coord, idx) => {
              const isPocActive = activePartState?.pocPoint === coord.pocPoint && coord.line === (activePartState.assemblyLine || '1VCON100') && !selectedCustomStation;

              return (
                <motion.g
                  key={`lf-poc-${coord.line}-${coord.pocPoint}-${idx}`}
                  animate={{ x: coord.x - 30, y: coord.y - 12 }}
                  transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
                  className="cursor-pointer"
                  onClick={() => {
                    setSelectedPartNo(coord.parts[0]);
                    setSelectedCustomStation(null);
                  }}
                >
                  <title>{`POC Station: ${coord.pocPoint}\nLine: ${coord.line}\nParts Assigned:\n${coord.parts.map(p => `• ${p}`).join('\n')}`}</title>
                  <rect
                    x="0"
                    y="0"
                    width="60"
                    height="24"
                    rx="5"
                    fill={isPocActive ? '#064e3b' : '#0f172a'}
                    stroke={isPocActive ? '#34d399' : coord.track === 'PL' ? '#10b981' : '#f97316'}
                    strokeWidth={isPocActive ? 2.5 : 1}
                    filter={isPocActive ? 'url(#glowGreenTL)' : undefined}
                  />
                  <text
                    x="30"
                    y="16"
                    fill={isPocActive ? '#34d399' : '#f3f4f6'}
                    fontSize="10"
                    fontWeight="extrabold"
                    textAnchor="middle"
                    fontFamily="monospace"
                  >
                    {coord.pocPoint}
                  </text>
                </motion.g>
              );
            })}
          </svg>
        </div>
      </div>

      {/* 4. STATION COVERAGE CARDS GRID (PL & ML BREAKDOWN) */}
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <h3 className="text-sm font-bold text-slate-900 dark:text-white font-mono uppercase tracking-wider flex items-center gap-2">
            <ShieldAlert className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
            POC STATION COVERAGE CARDS ({sortedInventoryStates.length} Stations)
          </h3>
          <span className="text-xs font-mono text-slate-500 dark:text-slate-400">
            Line: <strong className="text-emerald-600 dark:text-emerald-400">{selectedAssemblyLine}</strong> | Track: <strong className="text-cyan-600 dark:text-cyan-400">{selectedTrack}</strong>
          </span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          {sortedInventoryStates.map((state, idx) => {
            const part = parts.find((p) => p.partNo === state.partNo);
            const stationInfo = stations.find((s) => s.pocPoint === state.pocPoint);
            const pocUpper = state.pocPoint.toUpperCase();
            const isPL = pocUpper.startsWith('PL') || pocUpper.includes('PRE');
            const trackType = isPL ? 'PL Line (PL-01 to PL-29)' : 'ML Line (ML-01 to ML-48)';

            const pocSpaceTrolleysMax = part ? getPocSpaceTrolleysMax(part) : 1;
            const currentTrolleys = part && part.binCapacity > 0 ? Number((state.currentStockUnits / part.binCapacity).toFixed(2)) : 0;
            const spaceViolation = currentTrolleys > pocSpaceTrolleysMax;

            return (
              <div
                key={`${state.pocPoint}-${state.partNo}-${idx}`}
                className={`rounded-2xl p-4 border transition-all shadow-md flex flex-col justify-between ${
                  spaceViolation
                    ? 'bg-red-50 dark:bg-red-950/20 border-red-300 dark:border-red-500/60 shadow-red-500/10 animate-pulse'
                    : state.riskLevel === 'Green'
                    ? 'bg-white dark:bg-slate-900 border-slate-200 dark:border-emerald-500/30 hover:border-emerald-500'
                    : state.riskLevel === 'Yellow'
                    ? 'bg-amber-50/60 dark:bg-amber-950/20 border-amber-200 dark:border-amber-500/40 hover:border-amber-500'
                    : 'bg-rose-50/80 dark:bg-rose-950/30 border-rose-200 dark:border-rose-500/60'
                }`}
              >
                <div>
                  {/* Station Badge & Track Designation */}
                  <div className="flex items-center justify-between pb-2 border-b border-slate-200 dark:border-slate-800">
                    <span className="font-mono font-extrabold text-slate-900 dark:text-white text-sm flex items-center gap-1.5">
                      <MapPin className="w-3.5 h-3.5 text-cyan-600 dark:text-cyan-400" />
                      {state.pocPoint}
                    </span>
                    <span
                      className={`px-2 py-0.5 rounded-full text-[10px] font-extrabold uppercase tracking-wide border ${
                        spaceViolation
                          ? 'bg-red-100 dark:bg-red-500/30 text-red-700 dark:text-red-200 border-red-300 dark:border-red-500/50'
                          : state.riskLevel === 'Green'
                          ? 'bg-emerald-50 dark:bg-emerald-500/20 text-emerald-700 dark:text-emerald-300 border-emerald-200 dark:border-emerald-500/40'
                          : state.riskLevel === 'Yellow'
                          ? 'bg-amber-50 dark:bg-amber-500/20 text-amber-700 dark:text-amber-300 border-amber-200 dark:border-amber-500/40'
                          : 'bg-rose-50 dark:bg-rose-500/30 text-rose-700 dark:text-rose-200 border-rose-200 dark:border-rose-500/50'
                      }`}
                    >
                      {spaceViolation ? 'SPACE VIOLATION ⚠️' : state.riskLevel}
                    </span>
                  </div>

                  {/* Track Label */}
                  <div className="mt-2 flex items-center justify-between text-[10px] font-mono">
                    <span className={`px-2 py-0.5 rounded font-bold ${isPL ? 'bg-cyan-50 dark:bg-cyan-950 text-cyan-700 dark:text-cyan-300 border border-cyan-200 dark:border-cyan-800/50' : 'bg-purple-50 dark:bg-purple-950 text-purple-700 dark:text-purple-300 border border-purple-200 dark:border-purple-800/50'}`}>
                      {trackType}
                    </span>
                    <span className="text-amber-700 dark:text-amber-400 font-extrabold">{part?.loadedDistanceMeters || 194}M Travel</span>
                  </div>

                  <div className="mt-3">
                    <h4 className="text-xs font-bold text-slate-900 dark:text-white line-clamp-1">{stationInfo?.stationName || state.pocPoint}</h4>
                    <div className="text-[11px] font-mono text-emerald-700 dark:text-emerald-300 mt-0.5 truncate">{part?.description}</div>
                    <div className="flex items-center justify-between gap-1 mt-1">
                      <span className="text-[10px] text-slate-500 dark:text-slate-400 font-mono">Part: {state.partNo}</span>
                      <span className={`px-1.5 py-0.2 rounded text-[9px] font-mono font-bold border ${
                        part?.binOrTrolley === 'Carton'
                          ? 'bg-amber-100 text-amber-800 border-amber-300 dark:bg-amber-950/70 dark:text-amber-300 dark:border-amber-700/60'
                          : part?.binOrTrolley === 'Bin'
                          ? 'bg-emerald-100 text-emerald-800 border-emerald-300 dark:bg-emerald-950/70 dark:text-emerald-300 dark:border-emerald-700/60'
                          : 'bg-blue-100 text-blue-800 border-blue-300 dark:bg-blue-950/70 dark:text-blue-300 dark:border-blue-700/60'
                      }`} title={part?.binOrTrolley === 'Carton' ? 'Pre-packed inside carton box' : part?.binOrTrolley === 'Bin' ? 'Stored in bin on platform trolley' : 'Pre-loaded in dedicated trolley'}>
                        {part?.binOrTrolley === 'Carton' ? 'Carton Box' : part?.binOrTrolley === 'Bin' ? 'Bin (Platform)' : 'Trolley (Pre-loaded)'}
                      </span>
                    </div>
                  </div>

                  {/* Stock Gauge */}
                  <div className="mt-3 p-3 rounded-xl bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 space-y-2">
                    <div className="flex justify-between items-baseline">
                      <span className="text-xs text-slate-500 dark:text-slate-400">Current Stock:</span>
                      <span className="text-base font-extrabold text-slate-900 dark:text-white font-mono">{state.currentStockUnits} Units</span>
                    </div>

                    <div className="flex justify-between items-baseline">
                      <span className="text-xs text-slate-500 dark:text-slate-400">POC Space Limit:</span>
                      <span className={`text-xs font-mono font-bold ${spaceViolation ? 'text-red-600 dark:text-red-400' : 'text-slate-600 dark:text-slate-400'}`}>
                        {currentTrolleys}T / {pocSpaceTrolleysMax}T
                      </span>
                    </div>

                    <div className="flex justify-between items-baseline">
                      <span className="text-xs text-slate-500 dark:text-slate-400">Coverage:</span>
                      <span
                        className={`text-xs font-bold font-mono ${
                          state.riskLevel === 'Green'
                            ? 'text-emerald-600 dark:text-emerald-400'
                            : state.riskLevel === 'Yellow'
                            ? 'text-amber-600 dark:text-amber-400'
                            : 'text-rose-600 dark:text-rose-400'
                        }`}
                      >
                        {state.coverageHours} Hours
                      </span>
                    </div>

                    <div className="w-full bg-slate-200 dark:bg-slate-800 h-2 rounded-full overflow-hidden">
                      <div
                        className={`h-full transition-all duration-500 ${
                          state.riskLevel === 'Green'
                            ? 'bg-emerald-500'
                            : state.riskLevel === 'Yellow'
                            ? 'bg-amber-500'
                            : 'bg-rose-500'
                        }`}
                        style={{ width: `${Math.min(100, (state.coverageHours / 3) * 100)}%` }}
                      />
                    </div>
                  </div>
                </div>

                {/* Next Delivery & Dispatch Actions */}
                <div className="mt-4 pt-3 border-t border-slate-200 dark:border-slate-800 space-y-2">
                  <div className="flex justify-between items-center text-[10px] text-slate-500 dark:text-slate-400 font-mono">
                    <span>Next Dispatch:</span>
                    <span className="text-slate-800 dark:text-slate-200 font-medium">{state.nextDeliveryScheduledAt}</span>
                  </div>

                  <div className="flex items-center space-x-2">
                    <button
                      onClick={() => triggerManualReplenishment(state.partNo, 2)}
                      className="flex-1 py-1.5 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-xs shadow cursor-pointer transition-all"
                    >
                      +2 Trolleys
                    </button>
                    <button
                      onClick={() => dispatchEmergencyTrip(state.partNo)}
                      className="px-2.5 py-1.5 rounded-xl bg-rose-600 hover:bg-rose-500 text-white font-bold text-xs flex items-center justify-center gap-1 cursor-pointer transition-all"
                      title="Dispatch Emergency BOV Trip"
                    >
                      <Zap className="w-3.5 h-3.5" />
                    </button>
                  </div>
                </div>

              </div>
            );
          })}
        </div>
      </div>

    </div>
  );
};
